apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: clean-api-dev
  namespace: argocd
  
spec:
  project: clean-api
  source:
    repoURL: https://github.com/Evandro-zigzig/test_Argo.git
    targetRevision: main
    path: k8s/base
  destination:
    server: https://kubernetes.default.svc
    namespace: mentoria
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
