apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: clean-api-dev
  namespace: argocd
  
spec:
  project: clean-api
  source:
    repoURL: https://github.com/Evandro-zigzig/test_Argo
    targetRevision: develop
    path: k8s/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: development
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
