apiVersion: v1
kind: Service
metadata:
  name: clean-api
  namespace: mentoria
spec:
  selector:
    app: clean-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30000
  type: NodePort
